# NUX STUB CONFIGURATION
# This file may be overwritten automatically by nux.
# Do not edit this file.

{ ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./boot-configuration.nix
  ];
}
